spring.application.name=arena

spring.datasource.url=jdbc:mysql://localhost:3306/csjmu_arena
spring.datasource.username=root
spring.datasource.password=P@ssword970

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true